/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class libproceso_JavaProceso */

#ifndef _Included_libproceso_JavaProceso
#define _Included_libproceso_JavaProceso
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     libproceso_JavaProceso
 * Method:    algoritmo_Prioridades
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_libproceso_JavaProceso_algoritmo_1Prioridades
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
